id: P9798EEB8
initial_creation_type: ocr
source_metadata:
  volumes:
    6581757a85304de5b7debf09953550df:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
